### ISSUE TITLE
migrate  error, and resource file ?

### ISSUE THREAD

**Issue by DevilMorgan** [ZenNMS/ZenNMS#1]
please help me

**Comment by angelcamposm** [comment]
hI @DevilMorgan the APP is just in "work in progress" it is not functional at this moment, i work on it hard

**Comment by DevilMorgan** [comment]
hi,
how is the work going

**Comment by angelcamposm** [comment]
Hi,

currently, im working on a mappers for the snmp pollers to write results to database.
